### ISSUE TITLE
Can't exec "porechop"

### ISSUE THREAD

**Issue by antoine4ucsd** [langjidong/MAECI#1]
hello
I would like to test your new tool on my set of nanopore data.
I get the attached error when executing:

```
perl ./Multiple-Assembly-Integration.pl -fq ./fastq/SIV1C_run2_barcode46_merged.fq -path1 ~/miniconda2/envs/maeci_env/bin/canu  -path2 ~/miniconda2/envs/maeci_env/bin/flye -path3 ~/miniconda2/envs/maeci_env/bin/wtdbg2 -path4 ~/miniconda2/envs/maeci_env/bin/racon -genome_size 10m -ngs_polishing 0 -outputdir ./ -reference ./reference/KU89241.fasta  -process 16 > log 2>&1
```

anything I am missing?
would your tool accept fastq.gz files?

thank you!
[log.txt](https://github.com/langjidong/MAECI/files/9570222/log.txt)

**Comment by langjidong** [comment]
Thank you so much for using our MAECI!
Before using MAECI, you should and must install some used software, such as Porechop, assembly software, QUAST and so on, which your own preference. MAECI is an analytical pipeline, which is self-selective and flexible, but it should install some auxiliary software by users, you can check the main script.
Sorry for your trouble, and if you have any questions, plz let us know.  And we hope you can give us more suggestions.

**Comment by antoine4ucsd** [comment]
thanks. it would be nice to list all the necessary packages. quast was not listed? nanoplot?
I started processing my sample. it seems slow but no error yet. I will keep you posted
